#!/bin/bash

##############################################################################
# BRAINOPS REVENUE ENGINE - WEEKLY AUTOMATED REPORT
# Generates comprehensive weekly performance report
##############################################################################

REPORT_DIR="/home/matt-woodworth/dev/brainops-gumroad/reports"
mkdir -p "$REPORT_DIR"

WEEK_NUM=$(date +%U)
YEAR=$(date +%Y)
REPORT_FILE="$REPORT_DIR/week_${WEEK_NUM}_${YEAR}_report.md"

cat > "$REPORT_FILE" << EOF
# BrainOps Revenue Engine - Weekly Report

**Week:** $WEEK_NUM of $YEAR
**Generated:** $(date)

---

## 📊 EXECUTIVE SUMMARY

### Financial Performance
- **Total Revenue:** \$XXX
- **Number of Sales:** XX
- **Average Order Value:** \$XXX
- **Growth vs Last Week:** +XX%

### Top Metrics
- **Conversion Rate:** X.X%
- **Email Open Rate:** XX%
- **Email Click Rate:** X.X%
- **Social Engagement:** XXX interactions

---

## 💰 REVENUE BREAKDOWN

### By Product
| Product | Sales | Revenue | % of Total |
|---------|-------|---------|------------|
| Ultimate Bundle | X | \$XXX | XX% |
| SaaS ERP Starter | X | \$XXX | XX% |
| AI Orchestrator | X | \$XXX | XX% |
| Other Products | X | \$XXX | XX% |

### By Traffic Source
| Source | Sales | Revenue | % of Total |
|--------|-------|---------|------------|
| Email | X | \$XXX | XX% |
| Reddit | X | \$XXX | XX% |
| Social (LinkedIn/Twitter) | X | \$XXX | XX% |
| Hacker News | X | \$XXX | XX% |
| Direct | X | \$XXX | XX% |

---

## 📧 EMAIL PERFORMANCE

### Sequence Metrics (This Week)
| Email | Sent | Opened | Clicked | Converted |
|-------|------|--------|---------|-----------|
| Email 1: Launch | XXX | XX% | X.X% | X |
| Email 2: Code Products | XXX | XX% | X.X% | X |
| Email 3: Automation | XXX | XX% | X.X% | X |
| Email 4: AI Prompts | XXX | XX% | X.X% | X |
| Email 5: Final Call | XXX | XX% | X.X% | X |

### Key Insights
- Best performing email: [EMAIL NAME] (XX% open, X.X% click)
- Worst performing email: [EMAIL NAME] (XX% open, X.X% click)
- Total unsubscribes: X
- Net list growth: +XX subscribers

---

## 📱 SOCIAL MEDIA PERFORMANCE

### LinkedIn
- Posts published: X
- Total reach: XXX
- Engagements: XXX (XX likes, XX comments, XX shares)
- Profile views: XXX
- Sales attributed: X

### Twitter
- Posts published: X
- Impressions: XXX
- Engagements: XXX
- Followers gained: +XX
- Sales attributed: X

### Reddit
- Posts: X (r/SaaS, r/Entrepreneur, r/webdev)
- Total upvotes: XXX
- Comments: XXX
- Sales attributed: X

### Hacker News
- Posts: X
- Points: XXX
- Comments: XXX
- Front page?: Yes/No
- Sales attributed: X

---

## 🎯 MARKETING PERFORMANCE

### Top Performing Channels (by sales)
1. [CHANNEL] - X sales (\$XXX revenue)
2. [CHANNEL] - X sales (\$XXX revenue)
3. [CHANNEL] - X sales (\$XXX revenue)

### Top Performing Content
1. [POST/EMAIL TITLE] - XX clicks, X conversions
2. [POST/EMAIL TITLE] - XX clicks, X conversions
3. [POST/EMAIL TITLE] - XX clicks, X conversions

### LAUNCH20 Discount Code Usage
- Total uses: XX
- Revenue with discount: \$XXX
- Average discount amount: \$XX
- Code expires: [DATE]

---

## 💬 CUSTOMER FEEDBACK

### Support Tickets
- Total tickets: XX
- Download issues: X
- Technical help: X
- Refund requests: X
- General questions: X

### Average Response Time
- Target: < 4 hours
- Actual: X.X hours
- Met SLA: XX%

### Testimonials Collected
- New testimonials this week: X
- Total testimonials: X
- Average rating: X.X/5

### Top Customer Requests
1. [REQUEST]
2. [REQUEST]
3. [REQUEST]

---

## 📈 TRENDS & INSIGHTS

### What's Working
- [INSIGHT 1]
- [INSIGHT 2]
- [INSIGHT 3]

### What's Not Working
- [ISSUE 1]
- [ISSUE 2]
- [ISSUE 3]

### Unexpected Findings
- [FINDING 1]
- [FINDING 2]

---

## 🚀 ACTIONS FOR NEXT WEEK

### High Priority
- [ ] [ACTION ITEM]
- [ ] [ACTION ITEM]
- [ ] [ACTION ITEM]

### Medium Priority
- [ ] [ACTION ITEM]
- [ ] [ACTION ITEM]

### Low Priority
- [ ] [ACTION ITEM]

---

## 📊 GOALS TRACKING

### Week 1 Goals (Actual vs Target)
- Sales: XX / 10+ ✅/❌
- Revenue: \$XXX / \$2,000+ ✅/❌
- Email subscribers: XXX / 500+ ✅/❌
- Social engagement: XXX / 100+ ✅/❌

### Month 1 Projection
Based on current trajectory:
- Projected sales: ~XX (target: 50+)
- Projected revenue: ~\$XXX (target: \$10,000+)
- On track: ✅/❌

---

## 💡 RECOMMENDATIONS

### Immediate Actions (This Week)
1. [RECOMMENDATION]
2. [RECOMMENDATION]
3. [RECOMMENDATION]

### Strategic Actions (Next 2-4 Weeks)
1. [RECOMMENDATION]
2. [RECOMMENDATION]
3. [RECOMMENDATION]

---

## 📎 APPENDICES

### Data Sources
- Gumroad Analytics: https://gumroad.com/analytics
- ConvertKit Dashboard: https://app.convertkit.com/dashboard
- BrainOps Command Center: https://brainops-command-center.vercel.app
- Manual tracking: logs/gumroad_daily_sales.csv

### Report Generated By
- Script: scripts/weekly-report-automation.sh
- Data period: [START DATE] to [END DATE]
- Next report: Week $(($WEEK_NUM + 1)) ($YEAR)

---

*This is a template. Fill in actual data weekly from dashboards.*
EOF

echo "✅ Weekly Report Template Created: $REPORT_FILE"
echo ""
echo "📊 To create actual report:"
echo "   1. Gather data from Gumroad, ConvertKit, social media"
echo "   2. Edit: $REPORT_FILE"
echo "   3. Replace XXX placeholders with actual numbers"
echo "   4. Review insights and set next week actions"
echo ""
echo "🔄 Run this script weekly (Sunday evening recommended)"
